----------------------------------------------
-- Project: SCSQC
-- Author: Venkat Kaushik 
-- Purpose: DDL for QCM_META table
-- Created: Thu Jun 09 2016
----------------------------------------------

--------------------------------------------------------
--  DDL for Table QCM_META
--------------------------------------------------------

  CREATE TABLE "HSSC_ETL"."QCM_META" 
   (	"BATCH_ID" NUMBER, 
	"BATCH_TYPE" VARCHAR2(60 BYTE), 
	"BATCH_STATUS" VARCHAR2(1 BYTE), 
	"QCM_DAT_FNAME" VARCHAR2(60 BYTE), 
	"QCM_DAT_MOD" DATE, 
	"QCM_DAT_NREC" NUMBER, 
	"QCM_DAT_SIZE" FLOAT(126), 
	"QCM_DAT_RATE" FLOAT(126), 
	"QCM_RES_ARRIVAL" DATE, 
	"QCM_RES_MOD" DATE, 
	"QCM_RES_COMPL" DATE, 
	"QCM_RES_FNAME" VARCHAR2(60 BYTE), 
	"TX_START" DATE, 
	"TX_COMPL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL" ;

   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."BATCH_ID" IS 'Batch ID';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."BATCH_TYPE" IS 'SCSQC_QCM_EXTRACT';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."BATCH_STATUS" IS 'Batch Status';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_DAT_FNAME" IS 'Payload file name';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_DAT_MOD" IS 'Payload last modified time';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_DAT_NREC" IS 'Payload number of records';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_DAT_SIZE" IS 'Payload file size';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_DAT_RATE" IS 'Payload transfer rate';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_RES_ARRIVAL" IS 'Response file creation time';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_RES_MOD" IS 'Response file last modified time';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_RES_COMPL" IS 'Response file processing completion time';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."QCM_RES_FNAME" IS 'Response file name';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."TX_START" IS 'Transaction start time';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_META"."TX_COMPL" IS 'Transacion end time';
--------------------------------------------------------
--  DDL for Index PKC_BATCH_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSSC_ETL"."PKC_BATCH_ID" ON "HSSC_ETL"."QCM_META" ("BATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL" ;
--------------------------------------------------------
--  Constraints for Table QCM_META
--------------------------------------------------------

  ALTER TABLE "HSSC_ETL"."QCM_META" ADD CONSTRAINT "PKC_BATCH_ID" PRIMARY KEY ("BATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL"  ENABLE;
  ALTER TABLE "HSSC_ETL"."QCM_META" MODIFY ("BATCH_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HSSC_ETL"."QCM_META" MODIFY ("BATCH_ID" NOT NULL ENABLE);

