----------------------------------------------
-- Project: SCSQC
-- Author: Venkat Kaushik 
-- Purpose: DDL for QCM_CASE table
-- Created: Thu Jun 09 2016
----------------------------------------------


--------------------------------------------------------
--  DDL for Table QCM_CASE
--------------------------------------------------------

  CREATE TABLE "HSSC_ETL"."QCM_CASE" 
   (	"RES_CASE_ID" VARCHAR2(50 BYTE), 
	"LOCAL_CASE_ID" VARCHAR2(200 BYTE), 
	"BATCH_ID" NUMBER, 
	"VISIT_ID" NUMBER(22,0), 
	"HTB_ENC_ACT_ID" NUMBER(22,0), 
	"MPI_LID" VARCHAR2(25 BYTE), 
	"PROCEDURE_ID" NUMBER(22,0), 
	"DATASOURCE_ROOT" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL" ;

   COMMENT ON COLUMN "HSSC_ETL"."QCM_CASE"."RES_CASE_ID" IS 'QCM Case ID ';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_CASE"."LOCAL_CASE_ID" IS 'Local Case ID ';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_CASE"."BATCH_ID" IS 'Batch ID';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_CASE"."VISIT_ID" IS 'Visit ID (=VISIT.VISIT_ID)';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_CASE"."HTB_ENC_ACT_ID" IS 'Encounter Act ID (=VISIT.HTB_ENC_ACT_ID)';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_CASE"."MPI_LID" IS 'Medical Record Number (=PATIENT_ID_MAP.MPI_LID)';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_CASE"."PROCEDURE_ID" IS 'Procedure ID (=PROCEDURE.PROCEDURE_ID)';
   COMMENT ON COLUMN "HSSC_ETL"."QCM_CASE"."DATASOURCE_ROOT" IS 'Site ROOT (CDW.DATASOURCE.DATASOURCE_ROOT)';
--------------------------------------------------------
--  DDL for Index PKC_LOCAL_CASE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSSC_ETL"."PKC_LOCAL_CASE_ID" ON "HSSC_ETL"."QCM_CASE" ("LOCAL_CASE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL" ;
--------------------------------------------------------
--  Constraints for Table QCM_CASE
--------------------------------------------------------

  ALTER TABLE "HSSC_ETL"."QCM_CASE" ADD CONSTRAINT "PKC_LOCAL_CASE_ID" PRIMARY KEY ("LOCAL_CASE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL"  ENABLE;
  ALTER TABLE "HSSC_ETL"."QCM_CASE" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "HSSC_ETL"."QCM_CASE" MODIFY ("LOCAL_CASE_ID" NOT NULL ENABLE);
/*
--------------------------------------------------------
--  DDL for Trigger T_QCM_CASE_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HSSC_ETL"."T_QCM_CASE_BI" 
BEFORE INSERT
ON QCM_CASE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
begin
 if :new.local_case_id is null then
  select QCM_LCID_SEQ.nextval into :new.local_case_id from dual;
 end if;
end T_QCM_CASE_BI;
/
ALTER TRIGGER "HSSC_ETL"."T_QCM_CASE_BI" ENABLE;
*/
