----------------------------------------------
-- Project: SCSQC
-- Author: Venkat Kaushik 
-- Purpose: DDL for QCM_SITE table
-- Created: Thu Jun 09 2016
----------------------------------------------

--------------------------------------------------------
--  DDL for Table QCM_SITE
--------------------------------------------------------

  CREATE TABLE "HSSC_ETL"."QCM_SITE" 
   (	"RES_SITE" VARCHAR2(30 BYTE), 
	"DATASOURCE_ROOT" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL" ;
--------------------------------------------------------
--  DDL for Index PKC_RES_SITE
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSSC_ETL"."PKC_RES_SITE" ON "HSSC_ETL"."QCM_SITE" ("RES_SITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL" ;
--------------------------------------------------------
--  Constraints for Table QCM_SITE
--------------------------------------------------------

  ALTER TABLE "HSSC_ETL"."QCM_SITE" ADD CONSTRAINT "PKC_RES_SITE" PRIMARY KEY ("RES_SITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HSSC_ETL"  ENABLE;
  ALTER TABLE "HSSC_ETL"."QCM_SITE" MODIFY ("DATASOURCE_ROOT" NOT NULL ENABLE);

